%YAML 1.1
---

extends: default

ignore: |
  .cache/

rules:
  colons:
    max-spaces-after: 8
  document-end:
    present: false
  indentation:
    spaces: 2
  line-length:
    max: 250
    allow-non-breakable-inline-mappings: true
  truthy:
    check-keys: false
