---
name: Review

on:
  pull_request: null

concurrency:
  group: review-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

  languagetool:
    name: languagetool
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Run languagetool
        uses: reviewdog/action-languagetool@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Run markdownlint
        uses: reviewdog/action-markdownlint@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          markdownlint_flags: -s ./.mdl-style.rb .

  detect-secrets:
    name: detect-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Run detect-secrets
        uses: reviewdog/action-detect-secrets@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          detect_secrets_flags: --all-files --force-use-all-plugins --exclude-files '\.git/.*'

  check-labels:
    name: check-labels
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --no-root --only=dev
      - name: Run scripts/check-labels.py
        run: scripts/check-labels.py

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --no-root --only=dev
      - name: Run yamllint
        run: poetry run yamllint .

  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install python dependencies
        run: poetry install --no-root --only=dev
      - name: Run flake8
        run: poetry run flake8

  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install system dependencies
        run: sudo apt-get install -y libvirt-dev build-essential
      - name: Install python dependencies
        run: poetry install --no-root
      - name: Run mypy
        run: poetry run mypy

  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install system dependencies
        run: sudo apt-get install -y libvirt-daemon libvirt-daemon-driver-qemu libvirt-dev build-essential
      - name: Install python dependencies
        run: poetry install
      - name: Run pytest
        run: poetry run pytest -n logical --dist worksteal

  bandit:
    name: bandit
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install python dependencies
        run: poetry install --no-root --only=dev
      - name: Run mypy
        run: poetry run bandit -r .
